# Generated by Django 5.2.8 on 2026-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('have_budget', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=50, unique=True)),
                ('chassis', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('insurance', models.DateField()),
                ('yearly_taxes', models.DateField()),
                ('periodic_inspection', models.DateField()),
                ('municipal_tax', models.DateField(blank=True, null=True)),
                ('tachograph', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
