# Generated by Django 5.2.8 on 2026-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='periodic_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='yearly_taxes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
