# Generated by Django 5.2.8 on 2026-01-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('ADD', 'Shto'), ('REMOVE', 'Remove')], default='ADD', max_length=10),
        ),
    ]
