# Generated by Django 5.2.8 on 2026-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_budgetadjustment_adjustment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetadjustment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebudget',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
