# Generated by Django 5.2.8 on 2026-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_budgetadjustment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('ADD', 'Shto'), ('REMOVE', 'Zbrit')], default='ADD', max_length=10),
        ),
    ]
