# Generated by Django 5.2.8 on 2026-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_budgetadjustment_adjustment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetadjustment',
            name='note',
            field=models.CharField(blank=True, default='xxx', max_length=255),
            preserve_default=False,
        ),
    ]
