# Generated by Django 5.2.8 on 2026-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
