# Generated by Django 5.2.8 on 2026-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_depot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='description',
            field=models.TextField(blank=True, default='xxx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='xxx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnheader',
            name='notes',
            field=models.TextField(blank=True, default='xxx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalheader',
            name='notes',
            field=models.TextField(blank=True, default='xxx'),
            preserve_default=False,
        ),
    ]
