"""
Django settings for Elb_Ndertuesi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
load_dotenv()


LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "core:home"
LOGOUT_REDIRECT_URL = "accounts:login"

# Auto logout after inactivity (seconds)
SESSION_COOKIE_AGE = 15 * 60   # 15 minutes

SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.environ.get("DEBUG", "0") == "1"

SECRET_KEY = os.environ.get("SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY environment variable is required. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )




ALLOWED_HOSTS = [
    ".up.railway.app",
    "localhost",
    "127.0.0.1",
]

extra_hosts = os.environ.get("ALLOWED_HOSTS", "")
if extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in extra_hosts.split(",") if h.strip()]


CSRF_TRUSTED_ORIGINS = [
    "https://*.up.railway.app",
]
extra_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if extra_csrf:
    CSRF_TRUSTED_ORIGINS += [u.strip() for u in extra_csrf.split(",") if u.strip()]


CANONICAL_HOST = os.environ.get("CANONICAL_HOST", "")


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# HTTPS redirect - opt-in via environment variable
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "0") == "1"
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Security headers (production only)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_NAME = "sessionid_clone"
    CSRF_COOKIE_NAME = "csrftoken_clone"


CSRF_FAILURE_VIEW = "core.views.csrf_failure"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    "accounts.apps.AccountsConfig",
    'management',
    'core',
    'expenses',
    'fuel',
    'inventory',
    'audit',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "axes.middleware.AxesMiddleware",
    "audit.middleware.CaptureIPMiddleware",
    "accounts.middleware.LoginRequiredMiddleware",
]

# Authentication backends (axes must be first)
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

if CANONICAL_HOST:
    MIDDLEWARE.append("accounts.middleware.CanonicalHostMiddleware")

MIDDLEWARE += [
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]



ROOT_URLCONF = 'Elb_Ndertuesi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.employee_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'Elb_Ndertuesi.wsgi.application'

HANDLER403 = "core.views.permission_denied_view"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

if os.environ.get("DATABASE_URL"):
    # 🚀 Railway / Production
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            ssl_require=False,
        )
    }
else:
    # 💻 Local development PostgreSQL
    # All credentials MUST be set in .env file
    db_name = os.environ.get("POSTGRES_DB")
    db_user = os.environ.get("POSTGRES_USER")
    db_password = os.environ.get("POSTGRES_PASSWORD")

    if not all([db_name, db_user, db_password]):
        raise RuntimeError(
            "Database credentials missing. Set POSTGRES_DB, POSTGRES_USER, "
            "and POSTGRES_PASSWORD in your .env file."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_name,
            "USER": db_user,
            "PASSWORD": db_password,
            "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================
# DJANGO-AXES CONFIGURATION
# Rate limiting & account lockout
# ==========================

# Lock out after 5 failed login attempts
AXES_FAILURE_LIMIT = 5

# Lock out for 30 minutes (1800 seconds)
AXES_COOLOFF_TIME = 0.5  # hours (30 minutes)

# Lock out by username + IP combination (more secure)
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]

# Use X-Forwarded-For header for Railway proxy
AXES_IPWARE_PROXY_COUNT = 1
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "REMOTE_ADDR",
]

# Reset failed attempts on successful login
AXES_RESET_ON_SUCCESS = True

# Enable verbose logging for debugging (disable in production if too noisy)
AXES_VERBOSE = DEBUG

# Store access attempts in database
AXES_ENABLE_ACCESS_FAILURE_LOG = True

# Custom lockout template
AXES_LOCKOUT_TEMPLATE = "accounts/lockout.html"

# Whitelist localhost for development
if DEBUG:
    AXES_NEVER_LOCKOUT_WHITELIST = True
    AXES_IP_WHITELIST = ["127.0.0.1", "localhost"]