# Generated by Django 5.2.8 on 2026-01-06 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tank 1', max_length=50)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.fueltank')),
            ],
        ),
        migrations.CreateModel(
            name='FuelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee')),
                ('refill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.fuelentry')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.fueltank')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicle')),
            ],
        ),
    ]
