# Generated by Django 5.2.8 on 2026-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelentry_closed_at_fuelentry_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelusage',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fuelusage',
            name='project',
            field=models.CharField(blank=True, default='xxx', max_length=100),
            preserve_default=False,
        ),
    ]
