# Generated by Django 5.2.8 on 2026-01-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_alter_fuelusage_amount_alter_fuelusage_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelentry',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fuel.fueltank'),
        ),
        migrations.AlterField(
            model_name='fuelusage',
            name='refill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='fuel.fuelentry'),
        ),
        migrations.AddConstraint(
            model_name='fuelentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed', False)), fields=('tank',), name='unique_open_refill_per_tank'),
        ),
    ]
